server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/post-service?authSource=admin

app:
  services:
    profile:
      url: http://localhost:8081/profile
    file:
      url: http://localhost:8084/file
    friend:
      url: http://localhost:8087/friend