server:
  port: 8087
  servlet:
    context-path: /friend

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/zayden_addFriend"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    identity: http://localhost:8080/identity
    profile: http://localhost:8081/profile
